# Play Tools 服务端配置文件

# 数据库配置
database:
  user: root          # 数据库用户名
  password: "123456"  # 数据库密码
  host: mysql         # 数据库主机地址
  port: "3306"        # 数据库端口
  name: play_tools    # 数据库名称

# 服务器配置
server:
  host: 0.0.0.0       # 服务器监听地址 (0.0.0.0 表示监听所有网络接口)
  port: "8080"        # 服务器端口

# 微信小程序配置
wechat:
  appid: ""           # 小程序 AppID (在微信公众平台获取)
  secret: ""          # 小程序 AppSecret (在微信公众平台获取)

# 文件上传配置
upload:
  max_size: 5242880   # 最大文件大小：5MB (5 * 1024 * 1024)
  avatar_path: "./uploads/avatars" # 头像存储路径
